version: "2.0"
services:
  mysql-dev:
    image: mysql:8.0
    restart: always
    container_name: mysql_dev
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mysql-test:
    image: mysql:8.0
    container_name: mysql_test
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_TEST}
      MYSQL_USER: ${MYSQL_USER_TEST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_TEST}
