FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY test.js ./

EXPOSE 3000

ENV DB_HOST=localhost \
    DB_USERNAME=default_user \
    DB_PASSWORD=default_password \
    DB_DATABASE=default_db \
    DB_PORT=3306

CMD ["node", "test.js"]